/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employeemanagementsystem;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tharuka
 */
public class ManageEmployee extends javax.swing.JFrame {

    String empFile="Employee.txt";
    String deptFile="Department.txt";
    String desFile = "Designation.txt";
    String Filter="Filter.txt";
    DefaultTableModel model = null;
    
    public ManageEmployee() {
        initComponents();
        
        DBConnection db = new EmpDBConnection();
        jComboBoxDeptName.addItem("Select Department");
        db.fillComboFromFile(deptFile,jComboBoxDeptName);
        
        db.displayTable(jTableManageEmployee, empFile);
    }
    public void clear(){
        jTextFieldEmpID.setText("");
        jTextFieldEmpName.setText("");
        jComboBoxDeptName.setSelectedIndex(0);
        jComboBoxDesignation.setSelectedIndex(0);
        jTextFieldEPFNo.setText("");
        jTextFieldEmpPhoneNo.setText("");
        jTextFieldEmpEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEmpID = new javax.swing.JTextField();
        jTextFieldEmpName = new javax.swing.JTextField();
        jTextFieldEPFNo = new javax.swing.JTextField();
        jTextFieldEmpPhoneNo = new javax.swing.JTextField();
        jTextFieldEmpEmail = new javax.swing.JTextField();
        jComboBoxDeptName = new javax.swing.JComboBox<>();
        jComboBoxDesignation = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableManageEmployee = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabelUsernameEmp = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();
        jLabelManageDept = new javax.swing.JLabel();
        jLabelManageDes = new javax.swing.JLabel();
        jLabelManageUser = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));
        jPanel2.setForeground(new java.awt.Color(51, 0, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Manage Employee");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Employee ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Employee Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Department Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Designation");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("EPF Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Phone Number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Email");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jTextFieldEmpID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 170, 31));

        jTextFieldEmpName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldEmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 170, 31));

        jTextFieldEPFNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldEPFNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 140, 31));

        jTextFieldEmpPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldEmpPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 140, 31));

        jTextFieldEmpEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextFieldEmpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmpEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 140, 31));

        jComboBoxDeptName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jComboBoxDeptName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeptNameActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxDeptName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 170, 31));

        jComboBoxDesignation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(jComboBoxDesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, 31));

        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 60, 30));

        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 60, -1));

        jButtonClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonClear.setText("CLEAR");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 70, -1));

        jTableManageEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp ID", "Name", "Department", "Designation", "EPF No", "Phone No", "Email"
            }
        ));
        jTableManageEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableManageEmployeeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableManageEmployee);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 760, 205));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_account_circle_white_36dp.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabelUsernameEmp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelUsernameEmp.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsernameEmp.setText("User");
        jPanel1.add(jLabelUsernameEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 40, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_account_circle_white_36dp.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("User");

        jLabelHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/baseline_home_white_18.png"))); // NOI18N
        jLabelHome.setText("Home");
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        jLabelManageDept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelManageDept.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManageDept.setText("Manage Department");
        jLabelManageDept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManageDeptMouseClicked(evt);
            }
        });

        jLabelManageDes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelManageDes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManageDes.setText("Manage Designation");
        jLabelManageDes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManageDesMouseClicked(evt);
            }
        });

        jLabelManageUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelManageUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelManageUser.setText("Search Employee");
        jLabelManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManageUserMouseClicked(evt);
            }
        });

        jLabelLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogout.setText("Logout");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Studies");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Colombo Institute of Higher");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel4)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelManageDept, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelManageDes, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabelManageUser))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelLogout)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(37, 37, 37)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelManageDept)
                .addGap(18, 18, 18)
                .addComponent(jLabelManageDes)
                .addGap(18, 18, 18)
                .addComponent(jLabelManageUser)
                .addGap(12, 12, 12)
                .addComponent(jLabelLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if(jTextFieldEmpID.getText().equals("")||jTextFieldEmpName.getText().equals("")||
        jComboBoxDeptName.getSelectedItem().equals("")||jComboBoxDesignation.getSelectedItem().equals("")|| 
        jTextFieldEPFNo.getText().equals("")|| jTextFieldEmpEmail.getText().equals("")
        || jTextFieldEmpPhoneNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Enter All Details!!!");
            clear();
        }
        else
        {   
            Employee obj = new Employee();
            
            obj.setEmpID(jTextFieldEmpID.getText().toString());
            obj.setDeptName(jComboBoxDeptName.getSelectedItem().toString());
            obj.setDes(jComboBoxDesignation.getSelectedItem().toString());
            obj.setEmpName(jTextFieldEmpName.getText());
            obj.setEpfNo(jTextFieldEPFNo.getText());
            obj.setEmpEmail(jTextFieldEmpEmail.getText());
            obj.setEmpPhoneNo(jTextFieldEmpPhoneNo.getText());

            obj.addEmployee(obj);
            DBConnection myobj = new EmpDBConnection();
            myobj.displayTable(jTableManageEmployee, "Employee.txt");
            clear();
            
        
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTextFieldEmpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpEmailActionPerformed

    private void jComboBoxDeptNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeptNameActionPerformed
        jComboBoxDesignation.removeAllItems();
        jComboBoxDesignation.addItem("Select Designation");
        String deptName=jComboBoxDeptName.getSelectedItem().toString();
        
        
        DBConnection db = new EmpDBConnection();
        db.FilterData(deptName, desFile);
        db.fillComboFromFile(Filter,jComboBoxDesignation);
    }//GEN-LAST:event_jComboBoxDeptNameActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        if("".equals(jTextFieldEmpID.getText().toString())|| "".equals(jTextFieldEmpName.getText().toString())) {
            
            JOptionPane.showMessageDialog(null, "Select Item from the table to Update!", "Error!", JOptionPane.ERROR_MESSAGE);
            clear();
            
        }
        else {
            model =(DefaultTableModel) jTableManageEmployee.getModel();
            int i= jTableManageEmployee.getSelectedRow();
            
            
            String oldItemCode= model.getValueAt(i, 0).toString();
            String oldItemName=model.getValueAt(i, 1).toString();
        
            if(oldItemCode==null || oldItemName==null) {
                
                 JOptionPane.showMessageDialog(null, "Select Item to Update!", "Error!", JOptionPane.ERROR_MESSAGE);
            
            }else {
               DBConnection obj = new EmpDBConnection();

            
                String newLine= jTextFieldEmpID.getText().toString()+","+jTextFieldEmpName.getText().toString()+","+
                jComboBoxDeptName.getSelectedItem().toString()+","+jComboBoxDesignation.getSelectedItem().toString()
                +","+jTextFieldEPFNo.getText().toString()+","+jTextFieldEmpPhoneNo.getText().toString()+","+jTextFieldEmpEmail.getText().toString();
        
                
                obj.editData(oldItemCode, newLine,empFile);
                obj.displayTable(jTableManageEmployee,empFile);
                clear();
            }
            
            
        }
        
        
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTableManageEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableManageEmployeeMouseClicked
        model = (DefaultTableModel) jTableManageEmployee.getModel();

        
        int i= jTableManageEmployee.getSelectedRow();
        
        
            jTextFieldEmpID.setText(jTableManageEmployee.getValueAt(i, 0).toString());
            jTextFieldEmpName.setText(jTableManageEmployee.getValueAt(i, 1).toString());
            jComboBoxDeptName.setSelectedItem(jTableManageEmployee.getValueAt(i, 2).toString());
            jComboBoxDesignation.setSelectedItem(jTableManageEmployee.getValueAt(i, 3).toString());
            jTextFieldEPFNo.setText(jTableManageEmployee.getValueAt(i, 4).toString());
            jTextFieldEmpPhoneNo.setText(jTableManageEmployee.getValueAt(i, 5).toString());
            jTextFieldEmpEmail.setText(jTableManageEmployee.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTableManageEmployeeMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        if("".equals(jTextFieldEmpID.getText().toString())&& "".equals(jTextFieldEmpName.getText().toString())) {

            JOptionPane.showMessageDialog(null, "Enter Item Code or Item Name to Delete Item!", "Error!", JOptionPane.ERROR_MESSAGE);
            clear();
        }
        else{
            EmpDBConnection obj = new EmpDBConnection();

            obj.deleteData(jTextFieldEmpID.getText().toString(),empFile);

            clear();
            obj.displayTable(jTableManageEmployee,empFile);

        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        ManagerHomePage home = new ManagerHomePage();
        home.jLabelUsername.setText(jLabelUsernameEmp.getText().toString());
        home.show();
        dispose();
    }//GEN-LAST:event_jLabelHomeMouseClicked

    private void jLabelManageDeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManageDeptMouseClicked
        ManageDepartments manageDept = new ManageDepartments();
        manageDept.jLabelUsernameManageDep.setText(jLabelUsernameEmp.getText().toString());
        manageDept.show();
        dispose();
    }//GEN-LAST:event_jLabelManageDeptMouseClicked

    private void jLabelManageDesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManageDesMouseClicked
        ManageDesignations des= new ManageDesignations();
        des.jLabelUsernameDes.setText(jLabelUsernameEmp.getText().toString());
        des.show();
        dispose();
    }//GEN-LAST:event_jLabelManageDesMouseClicked

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        UserLogin login = new UserLogin();
        login.show();
        dispose();
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void jLabelManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManageUserMouseClicked
        SearchEmployee searchemp = new SearchEmployee();
        searchemp.jLabelUsernameAssist.setText(jLabelUsernameEmp.getText().toString());
        searchemp.show();
        dispose();
    }//GEN-LAST:event_jLabelManageUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBoxDeptName;
    private javax.swing.JComboBox<String> jComboBoxDesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelManageDept;
    private javax.swing.JLabel jLabelManageDes;
    private javax.swing.JLabel jLabelManageUser;
    public javax.swing.JLabel jLabelUsernameEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableManageEmployee;
    private javax.swing.JTextField jTextFieldEPFNo;
    private javax.swing.JTextField jTextFieldEmpEmail;
    private javax.swing.JTextField jTextFieldEmpID;
    private javax.swing.JTextField jTextFieldEmpName;
    private javax.swing.JTextField jTextFieldEmpPhoneNo;
    // End of variables declaration//GEN-END:variables
}
